# Generated by Django 5.0.4 on 2024-05-15 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("family_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phonenumber", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.user",
                    ),
                ),
            ],
            bases=("core.user",),
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.user",
                    ),
                ),
                ("personal_code", models.CharField(max_length=20)),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("planning", "Planning Expert"),
                            ("inspection", "Inspector"),
                            ("engineering", "Engineer"),
                        ],
                        max_length=11,
                    ),
                ),
                (
                    "job_authority",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("M2", "M2"),
                            ("M3", "M3"),
                            ("normal", "Normal"),
                        ],
                        default="normal",
                        max_length=11,
                    ),
                ),
                ("job_experience", models.TextField(blank=True, null=True)),
                ("username", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=255)),
            ],
            bases=("core.user",),
        ),
    ]
